version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambdaProducerStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g69u5obflr0i"
s3_prefix = "lambdaProducerStack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=339639471939.dkr.ecr.us-east-2.amazonaws.com/lambdaprojectproducer"]
